version: "3.7"
services:
  namenode:
    image: cjj2010/hadoop:3.2.0
    ports: 
        - "9870:9870"
        - "8088:8088"
    command: > 
      bash -c "hdfs namenode & yarn resourcemanager "
    hostname: hdfs-namenode

  datanode:
    image: cjj2010/hadoop:3.2.0
    depends_on: 
        - namenode
    command: >
      bash -c "hdfs datanode & yarn nodemanager "
    ports:
# The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
        - "9864"
    links:
        - namenode:hdfs-namenode


  secondarynamenode:
    image: cjj2010/hadoop:3.2.0
    command: hdfs secondarynamenode
    ports:
        - "9868:9868"
    links:
        - namenode:hdfs-namenode
